### ISSUE TITLE
Repartition does not work

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/mango#139]
The `--repartition` CLI option appears to produce an error at the moment and contrary to a recent discussion there does not seem to be any other CLI based `partition` parameter.

In at least one test it seemed like the number of partitions was lower than it ought to be given the number of executors cores, motivating the desire for this option to control partition number.

**Comment by erictu** [comment]
logged in #137

**Comment by akmorrow13** [comment]
Fixed #149

**Comment by akmorrow13** [comment]
Fixed #149
