### ISSUE TITLE
Hover over buttons on reads and variants page are not in correct location

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/mango#162]

**Comment by dorislee0309** [comment]
Tooltip appear below seems to look ok: should the tooltip be on the right hand side of the cursor? 
<img width="977" alt="screen shot 2016-05-02 at 10 54 25 pm" src="https://cloud.githubusercontent.com/assets/5554675/14975755/d4509746-10b9-11e6-93dc-905247c27967.png">

**Comment by akmorrow13** [comment]
That looks good. Then we know it is not overlapping anything
