### ISSUE TITLE
When no variants file is added /variants gives a 500

### ISSUE THREAD

**Issue by david4096** [bigdatagenomics/mango#173]
I ran mango on a few pieces of the GA4GH compliance [test data](https://github.com/ga4gh/compliance/tree/master/test-data). When I did not provide a VCF and tried browsing to the variants I got [this error](https://gist.github.com/david4096/bbc09d828ed1b2907f8c1e728f96df5b). It would be nice to gracefully fail when no variant data is made available.

Amazing stuff, can't wait to play around with it more!

**Comment by akmorrow13** [comment]
Hi David,

I completely agree. Some things are funky right now in the sake of finishing a paper. We will get that kink sorted out!
Best,

Alyssa Morrow
akmorrow@berkeley.edu <mailto:akmorrow@berkeley.edu>
414-254-6645

**Comment by erictu** [comment]
The error was due to an html template not being there. It has now been resolved, so that if you visit a region that doesn't have data, the frontend will still display, but without data.
