### ISSUE TITLE
minor frontend issues

### ISSUE THREAD

**Issue by dorisjlee** [bigdatagenomics/mango#195]
In order from most to least important issues:
- adjust spacing between reference and alignment 
- Remove top navigation bar since Overalls is now all on one page 
- Getting rid of “Loading alignment, Issued 1 request”  pileup icon (gui is jumpy when loading), bring back the beachball loading? 
- Optional type in text field rather than using selection box (bring back autocomplete and form checking functions)
- Pileup’s Alignment “View as pairs”, “Sort alignments” functionalities don’t work

**Comment by akmorrow13** [comment]
Separated out into multiple issues
