### ISSUE TITLE
GA4GH protobuf to JSON convert - need help

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/mango#279]
Please see this repo below which attempts to convert GA4GH defined object to JSON

https://github.com/jpdna/pb_to_json_test

clone and try to do:
```
mvn clean package
java -cp ./target/my-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.justinpaschall.app.App
```

The compile currently fails with this error:
```
[ERROR] /Users/paschalj/test9/demo_json_prob/v2/pb_to_json_test/src/main/java/org/justinpaschall/app/App.java:[35,61] incompatible types: ga4gh.Variants.Variant cannot be converted to com.google.protobuf.MessageOrBuilder
```
with this failing:

https://github.com/jpdna/pb_to_json_test/blob/master/src/main/java/org/justinpaschall/app/App.java#L35

The GA4GH extends `Variant` class `GeneratedMessageV3` but it is apparently not a `Message` of the type that the JSON printer wants.

Also you may need to build the GA4GH artifacts and install to your local maven repo using:https://github.com/ga4gh/ga4gh-schemas
I believe 
```
mvn clean install
```
in the ga4gh-schema repo will get those installed locally for you

Any help much appreciated.

**Comment by akmorrow13** [comment]
Hmm, that is very weird. I just ran it and it worked fine. However, I did have to modify the code by handing InvalidProtocolBufferException when trying to convert. Try changing  `com.google.protobuf.util.JsonFormat.printer().print(variant);`

to something like

```
        try {
            String x = com.google.protobuf.util.JsonFormat.printer().print(variant);
            System.out.println(x);
        } catch (InvalidProtocolBufferException ex) {
            System.out.println("error? unhandled");
        }
```

**Comment by akmorrow13** [comment]
Let me know if you still have issues!

**Comment by jpdna** [comment]
Works!  - with your exception handling.
Part of my problem also seemed to be solved by re-installed my GA4GH-schema artifact and doing 
```
mvn clean package -U
```

Thanks!
