### ISSUE TITLE
Off by one genomic position in Variants track in gui 

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/mango#290]
Running Mango master branch using the in repo example data:
```
./example-files/run-example.sh
```
I select a region to view in Mango GUI:
chr17: 7,501,828-7,501,840
![screen shot 2017-05-03 at 2 11 23 pm](https://cloud.githubusercontent.com/assets/7423296/25674829/48a9ad92-300a-11e7-98f2-662994d16542.png)

The data source for the variants track in this view is:
```
/mango/example-files/ALL.chr17.7500000-7515000.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf
```
and in that file the first columns of VCF for the example  variant here are
```
17      7501832 rs368364378     T       C       100     PASS
```

The API service GET endpoint returns:
```
curl 'http://localhost:8080/variants/ALL_chr17_7500000-7515000_phase3_shapeit2_mvncall_integrated_v5a_20130502_genotypes_vcf/chr17?end=7501900&start=7501759&binning=1'

[
  "{\"variant\":{\"contig\":\"chr17\",\"position\":7501831,\"end\":7501832,\"ref\":\"T\",\"alt\":\"C\"},\"sampleIds\":[]}",
  "{\"variant\":{\"contig\":\"chr17\",\"position\":7501886,\"end\":7501887,\"ref\":\"A\",\"alt\":\"G\"},\"sampleIds\":[]}"
]
```

The dbSNP record for this SNP is at:
https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=368364378

and reports this flanking sequence around the SNP:
```
ATGGCT[C/T]CTCAGTA
```

The SNP can be viewed at NCBI sviewer on GRCh37 here:
https://goo.gl/oo4NlG
![screen shot 2017-05-03 at 2 14 39 pm](https://cloud.githubusercontent.com/assets/7423296/25674969/c5a9a2b6-300a-11e7-8792-5035e1dcf9f9.png)

So, NCBI view agree with the VCF and report the variant as occurring in the second of the two consecutive "T" in "GGCTT"

The Mango view above puts the red bar for the variant under the first of these two "T", and appears to be shifted one base position less than it should.  The text pop up in the GUI reports zero-based coordinates:
```
{"contig":"chr17","position":7501831,"end":7501832,"ref":"T","alt":"C"}
```
which are likely not what user would expect, as they would expect VCF style 1-based coordinates.

These issues are related to 0 vs 1-based positioning systems, but most likely we want the view in Mango to be one-based, and the reference sequence Mango shows appears to be one-based, resulting in the the off-by-one above positioning of the red bar.

I'm not certain what the `position` vs `end` is intended to be in  defining a SNP in the pileup API service, but I assume `end` is non inclusive base after the variant, and `position` is the inclusive start position, and both appear to be shifted one base down, assuming the api json response here in one-based coordinates

**Comment by jpdna** [comment]
I'll have a PR with a fix later today.

**Comment by jpdna** [comment]
Given that GA4GH is zero based as @heuermh mentioned:
https://github.com/ga4gh/ga4gh-schemas/blob/master/src/main/proto/ga4gh/variants.proto#L168

perhaps this issue is best fixed in the mango client - and the server continues to serve 0-based

**Comment by jpdna** [comment]
@akmorrow13  - can you comment on: 

1) Do you  agree  that this off-by-one issue exists in current Mango?

2) Do you think we should fix in on the server side or the client?

Although my original PR seemed to fix the genome browser view in Mango,
https://github.com/bigdatagenomics/mango/pull/291

I see now that it causes existing tests to fail, and also would require updates to make queries 1-based as well.  Given goal of using GA4GH API between client and the server, and GA4GH  is zero based anyhow, I prefer changing the client, and it looks like modifying our fork of pileup.js, to accept a zero-based GA4GH input as a variant data source.

I'm happy to work on doing that, just want to check first if you agree with this approach or if you suggest something different.

**Comment by akmorrow13** [comment]
1. I agree this off by one issue exists. I experienced this same issue while taking some snapshots for reads and vcf a could days ago.

2. This is a Mango issue. If you load the vcf directly into pileup, the positioning is correct. See here:
![screen shot 2017-05-08 at 10 54 12 am](https://cloud.githubusercontent.com/assets/6503416/25812690/b6354850-33dc-11e7-9894-9575f233dd19.png)

The positioning is probably too hard coded into Mango right now, so it would be good to remove these anywhere. If GA4GH is indeed zero-based compared to vcf then it should be changed in the client.

**Comment by jpdna** [comment]
> The positioning is probably too hard coded into Mango right now, so it would be good to remove these anywhere.

Could you re-state what you mean by the sentence above- I don't quite follow.   
And when you say change in client - you are saying change in our fork of pileup ?

**Comment by akmorrow13** [comment]
This will change will go into https://github.com/akmorrow13/pileup.js

**Comment by akmorrow13** [comment]
closed by https://github.com/bigdatagenomics/mango/pull/299
