### ISSUE TITLE
Following zoom-in, parts of VCf blocks disappears in the UI

### ISSUE THREAD

**Issue by rlim19** [bigdatagenomics/mango#295]
We found that after zoom-in a region (e.g from 7,508,441-7,508,473, to 7,508,449-7,508,465), the VCF blocks, i;e, the green with yellow rectangular and the sample (HG00100) grey blocks are not being rendered.

The attachments below illustrate the above-mentioned scenario

## Before zoom-in
![beforezoom](https://cloud.githubusercontent.com/assets/1018902/26629402/8451dc62-4602-11e7-91bc-7a4551711ca1.png)

## After zoom-in
![afterzoom](https://cloud.githubusercontent.com/assets/1018902/26629407/8a358de0-4602-11e7-841f-187c323aec95.png)

Thank you in advance.

**Comment by shibuvp** [comment]
@rlim19 can you  post the mango-submit command

**Comment by rlim19** [comment]
MANGO_HOME=/opt/mango
MANGO_DATA=hdfs:/data/mango

$MANGO_HOME/bin/mango-submit $MANGO_HOME/example-files/hg19.17.2bit \
-genes http://www.biodalliance.org/datasets/ensGene.bb \
-reads $MANGO_DATA/example-files/chr17.7500000-7515000.bam.adam \
-variants $MANGO_DATA/example-files/ALL.chr17.7500000-7515000.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf \
-show_genotypes \
-discover \
-port 8070

Cheers

**Comment by shibuvp** [comment]
im getting this exception 
Exception in thread "main" java.io.FileNotFoundException: Couldn't find any files matching 
my mango-submit command ===============
 ./bin/mango-submit --master yarn-cluster --driver-memory 2g --executor-memory 2g  --  file://opt/Data/HumanBase/hg19/hg19.fa  -genes http://www.biodalliance.org/datasets/ensGene.bb -reads hdfs://master.hdp:8020/opt/small5.adam  -variants hdfs://master.hdp:8020/opt/sample/sorted.vcf  -show_genotypes -discover -port 8020

**Comment by shibuvp** [comment]
is it possible to run mango-submit using yarn cluster?

**Comment by akmorrow13** [comment]
Hi @shibuvp. Can you isolate which file cannot be found? Is it the reference, reads or variants?

You can run mango-submit on yarn cluster. Just like spark or adam shell, you can run
`./bin/mango-submit  --master yarn-client <other spark args here> -- <other mango arguments here>`

Just remember to use '--' to separate Spark and Mango arguments

**Comment by akmorrow13** [comment]
Closed by https://github.com/bigdatagenomics/mango/pull/299
Thanks for finding this @rlim19 !
