### ISSUE TITLE
Coverage plot in notebook

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/mango#298]
A nice use graph to show in a Mango/ADAM note book, would be something approximating the coverage plot below from the original GATK paper, along with some other reference data tracks.

Note - it would not necessarily need to be produced in pileup.js - in fact for some applications a publication quality static plot impage generated by R or matplot lib would be better
http://genome.cshlp.org/content/20/9/1297.full

![image](https://cloud.githubusercontent.com/assets/7423296/26787830/52dd97fe-49d9-11e7-8912-628af0b22e69.png)

**Comment by akmorrow13** [comment]
closed with https://github.com/bigdatagenomics/mango/pull/307
