### ISSUE TITLE
With VCF

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/mango#551]
@akmorrow13  Hi , can Mango work only with VCF?

**Comment by akmorrow13** [comment]
Hi @Rokshan2016, are you using the python tools or the browser?

The browser and Mango python tools support files listed here: https://bdg-mango.readthedocs.io/en/latest/files/file-support.html. This includes traditional formats (vcf, bed, bam) and ADAM specified parquet formats to optimize distributed storage. 

If you are just using the jupyter widgets alone, these only support traditional formats (vcf, bed, bam).
