### ISSUE TITLE
Mango with Data Proc

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/mango#552]
@akmorrow13  Hi I am trying to run Mango in Google data proc. I am not able to access this 

gs://mango-initialization-bucket/ .  

https://bdg-mango.readthedocs.io/en/latest/cloud/google-cloud.html#running-mango-notebook-on-a-dataproc-cluster

**Comment by akmorrow13** [comment]
Hi @Rokshan2016 I see you closed this issue, were you able to get it working?

**Comment by Rokshan2016** [comment]
@akmorrow13 Yea , I found this in the doc : "In order to access this bucket through the cloud dataproc cluster, it is necessary to give billing account manager permissions to dataproc-accounts.iam.gserviceaccount.com and compute@developer.gserviceaccount.com through the IAM console".  Will try this first. Thanks! :)
