### ISSUE TITLE
jupyterlab extension

### ISSUE THREAD

**Issue by ricky-lim** [bigdatagenomics/mango#553]
Feature request to support the usage with jupyter lab, please.

**Comment by akmorrow13** [comment]
Thanks for raising this @ricky-lim. What version of jupyter lab are you using? It looks like using ipywidgets with juyter lab is still having some compatibility issues. We can keep an eye on this.

**Comment by ricky-lim** [comment]
Thank you for the response. 

The version I used: 1.2.6.

I tested if the ipywidget works with my jupyter-lab setup 
```
import ipywidgets

ipywidgets.IntSlider()
```
Fortunately, the widget is rendered :)

Unfortunately, the genome browser was not yet rendered. The only message that was printed is: `Loading widget ....`

I tried to look into the browser's console, unfortunately no logs are printed.

I am sorry I could not help you with more information to solve the issues.

**Comment by akmorrow13** [comment]
Thanks for the information @ricky-lim this will be helpful.

**Comment by akmorrow13** [comment]
Addressed by https://github.com/bigdatagenomics/mango/pull/559

**Comment by akmorrow13** [comment]
Addded with https://github.com/bigdatagenomics/mango/pull/559. Will be pushed in the next release.
