### ISSUE TITLE
Support Scala 2.12/Spark 3.x in build

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/mango#561]
Scala 2.12/Spark 3.x is now supported upstream in ADAM with separate artifacts, as of release version 0.32.0.  What might be the plan for Scala 2.12/Spark 3.x in Mango?

**Comment by akmorrow13** [comment]
Thanks for addressing this @heuermh. I will look into it.

**Comment by akmorrow13** [comment]
Closed with https://github.com/bigdatagenomics/mango/pull/562
