### ISSUE TITLE
Lazy Materialization of Data

### ISSUE THREAD

**Issue by erictu** [bigdatagenomics/mango#71]
3 Part Hierarchy (Top down)

- [ ]  LazyMaterialization[V]
Where V is the datatype e.g. AlignmentRecord
This layer manages loading of data from disk in different ways (if it doesn't exist in the RDD)

- [ ] RDD[IntervalTreePartition[K, S, V]]
Where K is the key (interval of start and end), and S is the entity identifier.
This layer manages which data is stored in which partition.

- [ ] IntervalTreePartition[K, S, V]
Where K is the key (interval of start and end), and S is the entity identifier.
This layer manages putting and getting data by use of a 2-dimensional range index (interval).

**Comment by fnothaft** [comment]
SGTM. Out of you and @akmorrow13, who is doing what? Also, add an item for stubbing out the classes?

**Comment by erictu** [comment]
Solved by #74
