### ISSUE TITLE
Display sample name for each track of variants

### ISSUE THREAD

**Issue by erictu** [bigdatagenomics/mango#90]

**Comment by akmorrow13** [comment]
Backend part done

**Comment by rlim19** [comment]
We found that the display for the filename of the vcf seems to be cut-off at the margins.

Please find attached is the screenshot with the display marked with red rectangular.

![m2](https://cloud.githubusercontent.com/assets/1018902/26626090/5d7b67fe-45f6-11e7-85ce-03290118dd98.png)

Thank you in advance. We look forward to hearing from you.

Kind regards,

Ricky Lim

**Comment by akmorrow13** [comment]
Thanks @rlim19 ! This is actually a pileup.js issue. I have a PR here: https://github.com/hammerlab/pileup.js/pull/458

Once that is merged in a can integrate the changes here.

**Comment by akmorrow13** [comment]
Fixed with https://github.com/hammerlab/pileup.js/pull/458
