### ISSUE TITLE
mapping quality filter on overall not working 

### ISSUE THREAD

**Issue by dorislee0309** [bigdatagenomics/mango#97]

**Comment by akmorrow13** [comment]
This was due to version issues. Re pulling will fix this.

**Comment by dorislee0309** [comment]
The rendering function seems to be sending the JSON request but the data rendering isn't changed even if I try a quality filter of a large value (e.g. 100).

**Comment by akmorrow13** [comment]
When you hover over a read, does it display mapping quality?

**Comment by dorislee0309** [comment]
yeah its the third number that's on the read info right? 
So for "613f0AAXX100423:8:32:14692:15585", the quality is 32?
![screen shot 2016-03-12 at 5 13 15 pm](https://cloud.githubusercontent.com/assets/5554675/13726298/12083948-e876-11e5-99b4-367c64c6db12.png)
